"""Add status field in Task model

Revision ID: 07dc9f3b644b
Revises: 31bfdd35eb09
Create Date: 2021-08-27 21:09:56.684696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07dc9f3b644b'
down_revision = '31bfdd35eb09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'status')
    # ### end Alembic commands ###
